version: "2.0"

services:
  elasticsearch:
    build:
        context: .
        dockerfile: elastic
    ports:
      - 9200:9200
  kibana:
    build:
        context: .
        dockerfile: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200


